[tool.poetry]
name = "hci class"
version = "0.1.0"
description = ""
authors = ["Adora <im.stariluz@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pyqt5-tools = "^5.15.9.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
